// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA14KzPcXL_psvoGxNFSPfI9djrMG5o-TU',
    appId: '1:159865980813:web:e9eb20a899c5cfd6dedfc4',
    messagingSenderId: '159865980813',
    projectId: 'kalbaca-3fa08',
    authDomain: 'kalbaca-3fa08.firebaseapp.com',
    storageBucket: 'kalbaca-3fa08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbKyf6ubXRdsNmVW8eOfNzXpk380V_QoI',
    appId: '1:159865980813:android:1b57278da3f1ba20dedfc4',
    messagingSenderId: '159865980813',
    projectId: 'kalbaca-3fa08',
    storageBucket: 'kalbaca-3fa08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNHWSisvH1x9t0MG7-Ybc5jiBKFRUEtV8',
    appId: '1:159865980813:ios:ac02ec7ae8918c26dedfc4',
    messagingSenderId: '159865980813',
    projectId: 'kalbaca-3fa08',
    storageBucket: 'kalbaca-3fa08.firebasestorage.app',
    iosBundleId: 'com.example.kalbaca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNHWSisvH1x9t0MG7-Ybc5jiBKFRUEtV8',
    appId: '1:159865980813:ios:ac02ec7ae8918c26dedfc4',
    messagingSenderId: '159865980813',
    projectId: 'kalbaca-3fa08',
    storageBucket: 'kalbaca-3fa08.firebasestorage.app',
    iosBundleId: 'com.example.kalbaca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA14KzPcXL_psvoGxNFSPfI9djrMG5o-TU',
    appId: '1:159865980813:web:751cd1eaeb0bb993dedfc4',
    messagingSenderId: '159865980813',
    projectId: 'kalbaca-3fa08',
    authDomain: 'kalbaca-3fa08.firebaseapp.com',
    storageBucket: 'kalbaca-3fa08.firebasestorage.app',
  );
}
