import 'package:flutter/material.dart';
import 'package:kalbaca/core/constants/constants.dart';
import 'fluid_balance_simulation_screen.dart';
import 'adult_fluid_intake_balance_screen.dart';
import '../../../data/models/patient_balance_result.dart';
import '../../../data/repositories/balance_repository.dart';

class HasilBalanceScreen extends StatefulWidget {
  final double targetKebutuhanCairan;
  final double totalIntake;
  final double totalOutput;
  final String? patientName;
  final double? weightKg;
  final int? age;
  final double? normalIWL;
  final String? gender;

  const HasilBalanceScreen({
    Key? key,
    required this.targetKebutuhanCairan,
    required this.totalIntake,
    required this.totalOutput,
    this.patientName,
    this.weightKg,
    this.age,
    this.normalIWL,
    this.gender,
  }) : super(key: key);

  @override
  State<HasilBalanceScreen> createState() => _HasilBalanceScreenState();
}

class _HasilBalanceScreenState extends State<HasilBalanceScreen> {
  late double balance;
  int _selectedIndex = 0;
  final BalanceRepository _balanceRepository = BalanceRepository();
  bool _isSaving = false;

  @override
  void initState() {
    super.initState();
    balance = widget.totalIntake - widget.totalOutput;
  }

  Future<void> _saveBalanceResult() async {
    if (widget.patientName == null ||
        widget.weightKg == null ||
        widget.age == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Data pasien tidak lengkap'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    setState(() {
      _isSaving = true;
    });

    try {
      final balanceResult = PatientBalanceResult(
        id: '', // Will be generated by Firestore
        userId: '', // Will be set by service
        patientName: widget.patientName!,
        age: widget.age!,
        gender: widget.gender ?? 'Tidak diketahui',
        weight: widget.weightKg!,
        balanceType: 'adult',
        balanceData: {
          'targetKebutuhanCairan': widget.targetKebutuhanCairan,
          'totalIntake': widget.totalIntake,
          'totalOutput': widget.totalOutput,
          'balance': balance,
          'normalIWL': widget.normalIWL,
        },
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      await _balanceRepository.saveBalanceResult(balanceResult);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Data berhasil disimpan'),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Gagal menyimpan data: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isSaving = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.primaryBlue,
      body: SafeArea(
        child: Column(
          children: [
            _buildHeaderSection(),
            Expanded(
              child: Padding(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildTitleSection(),
                    const SizedBox(height: 16),
                    _buildResultSection(),
                    const Spacer(),
                    _buildActionButtons(),
                  ],
                ),
              ),
            ),
            _buildBottomNavigationBar(),
          ],
        ),
      ),
    );
  }

  // Header Section with Logo and Title
  Widget _buildHeaderSection() {
    return Padding(
      padding: const EdgeInsets.only(
        left: AppDimensions.homePaddingHorizontal,
        right: AppDimensions.homePaddingHorizontal,
        top: AppDimensions.homePaddingTop,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // User and Logo Row
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              // Back Button
              GestureDetector(
                onTap: () {
                  Navigator.pop(context);
                },
                child: Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: AppColors.white,
                    shape: BoxShape.circle,
                  ),
                  child: const Icon(
                    Icons.arrow_back,
                    color: Color(0xFF0047AB),
                    size: 24,
                  ),
                ),
              ),

              // App Logo
              Image.asset('assets/logo.png', width: 100, height: 100),
            ],
          ),

          const SizedBox(height: 16),

          const SizedBox(height: 24),

          // Page Title with Home Icon
          Row(
            children: [
              // Home Icon
              Container(
                width: 36,
                height: 36,
                decoration: const BoxDecoration(
                  color: AppColors.white,
                  shape: BoxShape.circle,
                ),
                child: const Center(
                  child: Icon(
                    Icons.home,
                    color: AppColors.primaryBlue,
                    size: 20,
                  ),
                ),
              ),

              const SizedBox(width: 12),

              // Page Title
              const Text(
                'Hasil Balance Cairan Dewasa',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildTitleSection() {
    return const SizedBox.shrink(); // No longer needed as title is now in header
  }

  Widget _buildResultSection() {
    return Column(
      children: [
        _buildResultCard(
          'Target Kebutuhan Cairan',
          widget.targetKebutuhanCairan.toStringAsFixed(0),
        ),
        const SizedBox(height: 8),
        _buildResultCard('Total Intake', widget.totalIntake.toStringAsFixed(0)),
        const SizedBox(height: 8),
        _buildResultCard('Total Output', widget.totalOutput.toStringAsFixed(0)),
        const SizedBox(height: 8),
        _buildResultCard(
          'Balance (+/-)',
          '${balance >= 0 ? '+' : ''}${balance.toStringAsFixed(0)}',
          isBalance: true,
        ),
      ],
    );
  }

  Widget _buildResultCard(
    String label,
    String value, {
    bool isBalance = false,
  }) {
    Color cardColor = Colors.white;
    Color textColor = Colors.black;

    if (isBalance) {
      if (balance > 0) {
        cardColor = Colors.green.shade100;
        textColor = Colors.green.shade800;
      } else if (balance < 0) {
        cardColor = Colors.red.shade100;
        textColor = Colors.red.shade800;
      }
    }

    return Container(
      height: 48,
      decoration: BoxDecoration(
        color: cardColor,
        borderRadius: BorderRadius.circular(8),
        border: isBalance
            ? Border.all(color: textColor.withOpacity(0.3))
            : null,
      ),
      padding: const EdgeInsets.symmetric(horizontal: 16),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(
            label,
            style: TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.w500,
              color: textColor,
            ),
          ),
          Row(
            children: [
              Text(
                value,
                style: TextStyle(
                  fontSize: 16,
                  fontWeight: isBalance ? FontWeight.bold : FontWeight.w500,
                  color: textColor,
                ),
              ),
              const SizedBox(width: 4),
              Text(
                'mL',
                style: TextStyle(
                  fontSize: 14,
                  color: isBalance ? textColor : const Color(0xFF0047AB),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildActionButtons() {
    return Column(
      children: [
        // Hapus and Simpan buttons row
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            ElevatedButton(
              onPressed: () {
                // Show confirmation dialog for delete
                showDialog(
                  context: context,
                  builder: (BuildContext context) {
                    return AlertDialog(
                      title: const Text('Hapus Data'),
                      content: const Text(
                        'Apakah Anda yakin ingin menghapus semua data?',
                      ),
                      actions: [
                        TextButton(
                          onPressed: () => Navigator.of(context).pop(),
                          child: const Text('Batal'),
                        ),
                        TextButton(
                          onPressed: () {
                            Navigator.of(context).pop();
                            // Navigate back to previous screen or clear data
                            Navigator.of(context).pop();
                          },
                          child: const Text('Hapus'),
                        ),
                      ],
                    );
                  },
                );
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.red,
                foregroundColor: Colors.white,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(20),
                ),
                padding: const EdgeInsets.symmetric(
                  horizontal: 24,
                  vertical: 12,
                ),
              ),
              child: const Text('Hapus'),
            ),
            ElevatedButton(
              onPressed: _isSaving ? null : _saveBalanceResult,
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.green,
                foregroundColor: Colors.white,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(20),
                ),
                padding: const EdgeInsets.symmetric(
                  horizontal: 24,
                  vertical: 12,
                ),
              ),
              child: _isSaving
                  ? const SizedBox(
                      width: 20,
                      height: 20,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                      ),
                    )
                  : const Text('Simpan'),
            ),
          ],
        ),
        const SizedBox(height: 16),
        // Simulasi button
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: () {
                // Navigate back to balance calculation screen if parameters are available
                if (widget.patientName != null &&
                    widget.weightKg != null &&
                    widget.age != null &&
                    widget.normalIWL != null) {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => AdultFluidIntakeBalanceScreen(
                        patientName: widget.patientName!,
                        weightKg: widget.weightKg!,
                        age: widget.age!,
                        normalIWL: widget.normalIWL!,
                        totalOutput: widget.totalOutput,
                        fluidRequirement: widget.targetKebutuhanCairan,
                        gender: widget.gender,
                      ),
                    ),
                  );
                } else {
                  // Fallback to simulation screen if parameters not available
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) =>
                          const FluidBalanceSimulationScreen(),
                    ),
                  );
                }
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.white,
                foregroundColor: const Color(0xFF0047AB),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(20),
                ),
                padding: const EdgeInsets.symmetric(
                  horizontal: 24,
                  vertical: 12,
                ),
              ),
              child: const Text('Simulasi'),
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildBottomNavigationBar() {
    return Container(
      height: AppDimensions.homeNavBarHeight,
      decoration: const BoxDecoration(
        color: AppColors.white,
        border: Border(top: BorderSide(color: AppColors.borderGray, width: 1)),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: [
          _buildNavItem(0, Icons.home),
          _buildNavItem(1, Icons.assignment),
          _buildNavItem(2, Icons.person),
        ],
      ),
    );
  }

  Widget _buildNavItem(int index, IconData icon) {
    final bool isSelected = _selectedIndex == index;

    return GestureDetector(
      onTap: () {
        setState(() {
          _selectedIndex = index;
        });

        // Navigate based on selected index
        switch (index) {
          case 0:
            // Navigate to Home
            Navigator.popUntil(context, (route) => route.isFirst);
            break;
          case 1:
            // Navigate to Data Hasil Balance via Home
            Navigator.popUntil(context, (route) => route.isFirst);
            // The HomeScreen will handle showing DataHasilBalanceScreen when index is 1
            break;
          case 2:
            // Navigate to Profile via Home
            Navigator.popUntil(context, (route) => route.isFirst);
            // The HomeScreen will handle showing ProfileScreen when index is 2
            break;
        }
      },
      child: Container(
        color: Colors.transparent,
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        child: Icon(
          icon,
          color: isSelected ? AppColors.activeBlack : AppColors.inactiveGray,
          size: 28,
        ),
      ),
    );
  }
}
